# auth_key.toml

ver = "0.0.1"
serverId = 1
keyFile = "server_pkcs1.key"
KeyFingerprint = "2066079364791309323"

[server.server]
name = "handshake"
protoName = "brpc"
addr = "0.0.0.0:10005"

[authSessionRpcClient]
serviceName = "auth_session"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[server.discovery]
serviceName = "handshake"
nodeID = "node1"
rPCAddr = "127.0.0.1:10005"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"
